language: go

go:
  - 1.7
  - tip

matrix:
    allow_failures:
        - go: tip

install:
  - go get -t -v .
  - go get -t -v ./generator/...

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
